version: '3.7'

services:
  app:
    container_name: fir_app
    build:
      context: .
      target: node
      dockerfile: Dockerfile
    volumes:
      - .:/home/node/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    env_file: 
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
